name: Node.js CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - name: Build
        run: npm ci && next build && next export
      - name: Deploy
        uses: actions/deploy-pages@v4
        with:
          github-token: ${{ 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 }}
          branch: main
          root: public